[versions]
h2 = "2.4.240"
loom = "1.11-SNAPSHOT"
minecraft = "1.21.5"
yarn = "1.21.5+build.1"
loader = "0.16.14"
publish = "0.8.4"
maven = "0.34.0"

[libraries]
h2 = { module = "com.h2database:h2", version.ref = "h2" }
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }
fabric-yarn = { module = "net.fabricmc:yarn", version.ref = "yarn" }
fabric-loader = { module = "net.fabricmc:fabric-loader", version.ref = "loader" }

[plugins]
loom = { id = "fabric-loom", version.ref = "loom" }
publish = { id = "me.modmuss50.mod-publish-plugin", version.ref = "publish" }
maven = { id = "com.vanniktech.maven.publish", version.ref = "maven" }
